import Foundation

// MARK: - Benchmark Data
// Ported from benchmarks/lite_latency_bench.py
// 500 realistic personal memories + 100 search queries

enum BenchmarkData {

    static let memories: [String] = [
        // Daily life & routines
        "I usually wake up at 7am and make a pour-over coffee before checking emails.",
        "My morning routine includes 20 minutes of meditation and stretching.",
        "I switched from coffee to matcha for a month but went back to coffee.",
        "I take the subway line 2 to work every weekday, about 40 minutes each way.",
        "I started meal-prepping on Sundays to save time during the week.",
        "I bought a standing desk last month and love working while standing.",
        "My favorite lunch spot near the office is a small Vietnamese pho place.",
        "I usually go to bed around 11:30pm on weekdays.",
        "I've been trying to drink 8 glasses of water daily.",
        "I keep a gratitude journal and write in it before bed.",

        // Work & career
        "I'm a backend engineer at a mid-size startup working on recommendation systems.",
        "We migrated our backend from Python to Rust for performance reasons.",
        "My team uses Scrum with two-week sprints and daily standups at 10am.",
        "I got promoted to senior engineer last quarter after the system redesign project.",
        "I'm mentoring two junior developers on the team.",
        "We had a major production outage last Tuesday caused by a database migration.",
        "Our tech stack includes Rust, PostgreSQL, Redis, and Kubernetes.",
        "I presented at the company all-hands about our new caching architecture.",
        "I'm considering switching to a role that focuses more on machine learning.",
        "My annual review is coming up next month and I need to prepare my self-evaluation.",

        // Relationships & people
        "Alice is my best friend from college. We studied computer science together.",
        "My sister Emma lives in Tokyo and works as a translator.",
        "Bob is my teammate who always brings homemade cookies to the office.",
        "I met my partner Sarah at a hiking meetup three years ago.",
        "My mom calls me every Sunday afternoon to catch up.",
        "David is my neighbor who has two golden retrievers named Max and Luna.",
        "My college roommate James just got married last weekend.",
        "I have a monthly dinner with my high school friends group.",
        "My manager Lisa is very supportive and encourages continuous learning.",
        "I reconnected with my childhood friend Tom on social media.",

        // Hobbies & interests
        "I've been learning to play guitar for the past six months.",
        "I enjoy landscape photography, especially during golden hour.",
        "I read about 2-3 books per month, mostly science fiction and non-fiction.",
        "I started rock climbing at the local gym twice a week.",
        "I collect vinyl records, mostly jazz and classic rock.",
        "I've been experimenting with sourdough bread baking.",
        "I enjoy hiking and try to do a new trail every other weekend.",
        "I'm learning Japanese on Duolingo, currently on a 200-day streak.",
        "I like to sketch in cafes on Saturday mornings.",
        "I joined a local chess club and play rated games on weekends.",

        // Travel & experiences
        "I visited Kyoto last spring and loved the bamboo forest.",
        "My best travel memory is watching the northern lights in Iceland.",
        "I'm planning a road trip along the California coast next summer.",
        "I went scuba diving in the Maldives and saw manta rays.",
        "I spent two weeks in Barcelona learning about Gaudí's architecture.",
        "My family takes an annual trip to the lake house in Vermont.",
        "I flew business class for the first time on the Tokyo trip and it was amazing.",
        "I want to visit Patagonia for trekking next year.",
        "I did a solo backpacking trip through Southeast Asia after graduation.",
        "The night market in Taipei had the best street food I've ever had.",

        // Health & fitness
        "I run 5K three times a week, usually in the morning.",
        "I injured my left knee while playing basketball last year.",
        "I've been doing yoga for stress relief and flexibility.",
        "My doctor recommended I eat more iron-rich foods.",
        "I completed my first half marathon with a time of 1:52.",
        "I'm allergic to shellfish and carry an EpiPen.",
        "I switched to a plant-based diet for environmental reasons.",
        "I wear contact lenses but prefer glasses when working from home.",
        "I had a minor surgery on my wrist last summer for carpal tunnel.",
        "I track my sleep with a smartwatch and average about 7 hours.",

        // Food & cooking
        "My favorite cuisine is Thai food, especially green curry.",
        "I make pasta from scratch when I have time on weekends.",
        "I discovered an amazing ramen place called Ichiran near downtown.",
        "I don't like cilantro - it tastes like soap to me.",
        "I'm a big fan of Ethiopian food, especially injera with various stews.",
        "I brew my own kombucha at home.",
        "I tried making croissants from scratch and it took 3 days.",
        "My go-to comfort food is my grandmother's chicken soup recipe.",
        "I've been experimenting with fermented foods like kimchi and sauerkraut.",
        "I usually order a flat white when I go to coffee shops.",

        // Technology & gadgets
        "I built my own mechanical keyboard with Cherry MX Blue switches.",
        "I use a MacBook Pro for work and a custom Linux PC at home.",
        "I set up a home server with Proxmox for running various services.",
        "I'm interested in local-first software and CRDTs.",
        "I have a Raspberry Pi running Pi-hole for ad blocking at home.",
        "I switched to Firefox from Chrome for better privacy.",
        "I use Obsidian for personal knowledge management.",
        "I recently got a Steam Deck and play indie games on it.",
        "I prefer vim keybindings and use Neovim as my primary editor.",
        "I automated my home lights with Home Assistant and Zigbee bulbs.",

        // Finance & goals
        "I'm saving for a down payment on a condo in the city.",
        "I invest in index funds through a Vanguard account.",
        "I set a goal to save 30% of my income this year.",
        "I paid off my student loans last year after 5 years of payments.",
        "I track my expenses using a spreadsheet I update weekly.",
        "I'm considering buying an electric car, looking at the Tesla Model 3.",
        "I donate 5% of my income to environmental charities.",
        "I have an emergency fund covering 6 months of expenses.",
        "I want to retire by 55 if possible.",
        "I recently started contributing to my company's 401k match program.",

        // Pets & animals
        "I adopted a tabby cat named Mochi from the local shelter.",
        "Mochi loves to sit on my keyboard while I'm working.",
        "I'm thinking about getting a second cat to keep Mochi company.",
        "I volunteer at the animal shelter on the first Saturday of each month.",
        "I grew up with two dogs, a labrador and a beagle.",
        "I'm slightly allergic to dogs but take antihistamines around them.",
        "Mochi's favorite toy is a feather wand that I bought at the pet store.",
        "I take Mochi to the vet every six months for checkups.",
        "I feed Mochi a mix of wet and dry food, grain-free.",
        "My neighbor's cat and Mochi are friends and they sit by the window together.",

        // Entertainment & media
        "My favorite TV show of all time is Breaking Bad.",
        "I'm currently watching the latest season of Severance on Apple TV.",
        "I listen to a lot of podcasts during my commute, mostly tech and history.",
        "My favorite band is Radiohead and I've seen them live three times.",
        "I re-read The Lord of the Rings every few years.",
        "I went to a jazz concert at the Blue Note last Friday night.",
        "I subscribe to Netflix, HBO Max, and Apple TV+.",
        "My favorite movie genre is sci-fi, especially hard sci-fi like Arrival.",
        "I started watching anime recently and really enjoyed Attack on Titan.",
        "I listen to lo-fi hip hop while coding for focus.",

        // Home & living
        "I live in a one-bedroom apartment in downtown Seattle.",
        "I'm growing herbs on my windowsill - basil, rosemary, and mint.",
        "I bought a new couch last month, a navy blue sectional from IKEA.",
        "I painted my home office walls a calming sage green color.",
        "My apartment has a small balcony where I grow tomatoes in summer.",
        "I need to fix the leaky faucet in the bathroom this weekend.",
        "I installed blackout curtains in the bedroom for better sleep.",
        "I'm considering getting a robot vacuum for daily cleaning.",
        "My lease is up in September and I'm debating whether to renew.",
        "I reorganized my bookshelf by color and it looks great.",

        // Education & learning
        "I graduated from University of Washington with a CS degree in 2019.",
        "I'm taking an online course on machine learning from Stanford.",
        "I attended a Rust conference in Portland last month.",
        "I read research papers on graph neural networks in my spare time.",
        "I completed the Advent of Code challenge last December.",
        "I'm working through the Crafting Interpreters book for fun.",
        "I got AWS Solutions Architect certification last year.",
        "I want to learn more about distributed systems and consensus algorithms.",
        "I participated in a hackathon and our team built a transit app.",
        "I'm interested in taking a sabbatical to do a research internship.",

        // Weather & seasons
        "I love autumn in Seattle when the leaves change color.",
        "The rainy season here makes me want to stay inside and read.",
        "I bought a full-spectrum light for the dark winter months.",
        "Summer is my favorite season because I can hike and swim outdoors.",
        "Last winter was unusually cold and we had snow for a week.",
        "I enjoy watching thunderstorms from my apartment window.",
        "I always carry an umbrella in my bag just in case.",
        "The cherry blossoms at the university campus are beautiful in March.",
        "I find it hard to wake up when it's still dark outside in winter.",
        "I planned a ski trip to Whistler for January.",

        // Social & community
        "I volunteer at a coding bootcamp teaching Python basics.",
        "I organized a neighborhood cleanup event last month.",
        "I'm part of a book club that meets every third Thursday.",
        "I go to a weekly board game night at a local cafe.",
        "I helped set up a community garden in our apartment complex.",
        "I attend a monthly tech meetup focused on systems programming.",
        "I donated old clothes and books to Goodwill last weekend.",
        "I signed up to be a Big Brother mentor through a local nonprofit.",
        "I participated in a charity run for cancer research.",
        "I joined a co-working space to work from on Fridays.",

        // Memories & nostalgia
        "I remember building blanket forts with my sister when we were kids.",
        "My grandfather taught me to fish at the lake near his house.",
        "I still have the first program I ever wrote - a tic-tac-toe game in Python.",
        "The smell of cinnamon reminds me of my grandmother's apple pie.",
        "I used to collect Pokémon cards in elementary school.",
        "My first car was a beat-up Honda Civic that I drove through college.",
        "I have a box of letters my pen pal from France sent me in high school.",
        "My dad used to take me stargazing in the backyard every summer.",
        "I won a spelling bee in 5th grade and still have the trophy.",
        "Family road trips to the coast were my favorite childhood memories.",

        // Current events & opinions
        "I think remote work should be the default for knowledge workers.",
        "I'm concerned about climate change and try to reduce my carbon footprint.",
        "I believe in the importance of open-source software.",
        "I think AI will fundamentally change how we interact with computers.",
        "I prefer reading physical books over e-books.",
        "I believe everyone should learn basic coding skills.",
        "I think public transportation should be free and widely available.",
        "I'm optimistic about renewable energy adoption.",
        "I value privacy and use end-to-end encrypted messaging apps.",
        "I think the four-day work week would improve productivity.",

        // Plans & aspirations
        "I want to write a technical blog and share my learnings.",
        "I'm planning to build a side project using WebAssembly.",
        "I hope to run a full marathon by next year.",
        "I want to learn to surf on my next trip to Hawaii.",
        "I'm thinking about getting a master's degree in AI.",
        "I plan to visit all 50 US states - I've been to 32 so far.",
        "I want to build a tiny house someday.",
        "I'm considering starting a small consulting business on the side.",
        "I hope to write a science fiction novel eventually.",
        "I want to adopt a dog once I move to a bigger place.",

        // Miscellaneous personal details
        "My blood type is O positive.",
        "I'm left-handed but use a mouse with my right hand.",
        "My favorite color is deep ocean blue.",
        "I wear size 10 US shoes.",
        "My birthday is on March 15th - the Ides of March.",
        "I'm an introvert but enjoy small group gatherings.",
        "I have a fear of heights but love flying in airplanes.",
        "I always set my thermostat to 68°F in winter.",
        "I prefer window seats on flights.",
        "I'm a morning person and do my best work before noon.",

        // More work context
        "We use GitHub for version control and I have over 3000 contributions.",
        "I wrote a CLI tool in Rust that automates our deployment process.",
        "Our product serves about 2 million monthly active users.",
        "I debug production issues using distributed tracing with Jaeger.",
        "I'm working on improving our API response time from 200ms to under 50ms.",
        "We switched from REST to gRPC for internal service communication.",
        "I wrote comprehensive documentation for our new microservice architecture.",
        "Our team won the internal hackathon with an AI-powered code review tool.",
        "I set up the CI/CD pipeline using GitHub Actions.",
        "I'm responsible for the caching layer that reduced our database load by 60%.",

        // More food
        "I tried a new recipe for homemade pizza last night with a thin crust.",
        "My favorite breakfast is avocado toast with a poached egg.",
        "I discovered that adding a pinch of salt to coffee reduces bitterness.",
        "I make a great risotto with wild mushrooms and parmesan.",
        "I've been buying groceries from a local farmers market on Saturdays.",
        "I tried durian for the first time and actually liked it.",
        "My partner and I have a tradition of cooking a new cuisine every month.",
        "I freeze leftover soups in mason jars for quick weekday lunches.",
        "I prefer dark chocolate over milk chocolate, at least 70% cacao.",
        "I make cold brew coffee in large batches every Sunday.",

        // More relationships
        "My cousin Alex is a doctor in Boston and we catch up monthly.",
        "Sarah and I are celebrating our 3rd anniversary next month.",
        "I met my friend group 'The Wanderers' through a hiking app.",
        "My uncle runs a small bookshop in Portland that I visit every summer.",
        "I have a pen pal in Japan named Yuki who I've been writing to for 5 years.",
        "My coworker Priya and I started a lunch running club.",
        "My brother is 5 years younger and just started university.",
        "I have a close friend Carlos who is a professional photographer.",
        "My grandmother is 92 and still gardens every day.",
        "Sarah's parents live in Portland and we visit them on holidays.",

        // More hobbies
        "I started learning 3D printing and printed a phone stand as my first project.",
        "I play competitive table tennis at a local club.",
        "I enjoy solving crossword puzzles in the morning paper.",
        "I've been collecting first edition books, mostly sci-fi classics.",
        "I taught myself to juggle during the pandemic lockdowns.",
        "I enjoy birdwatching and have identified over 50 species in our area.",
        "I started a small herb garden on my balcony.",
        "I make pour-over coffee and have experimented with different grind sizes.",
        "I enjoy doing jigsaw puzzles on rainy weekend afternoons.",
        "I recently picked up calligraphy and practice brush lettering.",

        // More tech
        "I contributed to an open-source Rust project for the first time last month.",
        "I'm experimenting with local LLMs using Ollama on my home server.",
        "I use tmux for terminal multiplexing and have a custom configuration.",
        "I set up Tailscale for secure access to my home network.",
        "I'm interested in WASM as a universal runtime.",
        "I built a personal website using Astro and deployed it on Vercel.",
        "I use pass for password management with GPG encryption.",
        "I automated my backups using restic to a local NAS.",
        "I set up monitoring for my home server using Grafana and Prometheus.",
        "I'm following the development of Zig language with interest.",

        // More health
        "I started taking vitamin D supplements during the winter months.",
        "I do 10 minutes of stretching every morning to prevent back pain.",
        "I switched to a ergonomic split keyboard to reduce wrist strain.",
        "I practice deep breathing exercises when I feel stressed.",
        "I got my annual flu shot at the pharmacy last week.",
        "I've been reducing my screen time before bed and reading instead.",
        "I keep a food diary to track how different foods affect my energy.",
        "I see a therapist every two weeks for general mental wellness.",
        "I take magnesium before bed to improve sleep quality.",
        "I do a digital detox every first weekend of the month.",

        // More daily life
        "I take a 15-minute power nap after lunch when working from home.",
        "I organize my tasks using the Pomodoro technique.",
        "I keep my phone on Do Not Disturb mode during work hours.",
        "I batch process emails twice a day instead of checking constantly.",
        "I take cold showers in the morning to boost alertness.",
        "I walk to a different coffee shop each week to explore the neighborhood.",
        "I set weekly goals every Monday morning in my planner.",
        "I unsubscribed from most marketing emails to reduce inbox clutter.",
        "I use noise-canceling headphones while working in the office.",
        "I try to take a walk outside during my lunch break every day.",

        // More experiences
        "I attended a wine tasting event in Napa Valley last October.",
        "I tried indoor skydiving and it was an incredible adrenaline rush.",
        "I took a pottery class and made a wobbly but charming mug.",
        "I went kayaking on Puget Sound and saw seals sunbathing on rocks.",
        "I attended a cheese-making workshop and brought home fresh mozzarella.",
        "I saw the total solar eclipse in 2024 and it was life-changing.",
        "I tried ax throwing at a bar and it was surprisingly fun.",
        "I went to a silent disco and loved the experience.",
        "I took a glassblowing class and made a small paperweight.",
        "I visited a lavender farm during peak bloom season.",

        // Fill to 500
        "I keep a dream journal and write down my dreams every morning.",
        "I have a collection of vintage maps on my office wall.",
        "I listen to nature sounds while falling asleep.",
        "I always carry a reusable water bottle and tote bag.",
        "I prefer natural lighting and sit near windows whenever possible.",
        "I have a small succulent collection on my desk.",
        "I organized a potluck dinner with colleagues last Friday.",
        "I'm teaching Mochi to high-five and she's almost got it.",
        "I prefer taking stairs over elevators when it's less than 5 floors.",
        "I write morning pages - three pages of stream-of-consciousness journaling.",
        "I switched to bamboo toothbrushes to reduce plastic waste.",
        "I buy locally roasted coffee beans from a shop called Elm Coffee Roasters.",
        "I have a whiteboard in my home office for brainstorming.",
        "I enjoy watching cooking competition shows like MasterChef.",
        "I started a habit of reading for 30 minutes before bed.",
        "I keep emergency snacks in my desk drawer at work.",
        "I practice touch typing and can type about 100 WPM.",
        "I wear a fitness tracker and aim for 10000 steps daily.",
        "I subscribed to a monthly book box that sends curated novels.",
        "I installed a water filter in my kitchen for better tasting water.",
        "I use a French press for coffee on weekends when I have more time.",
        "I keep a running list of movies to watch on Letterboxd.",
        "I enjoy visiting botanical gardens in different cities.",
        "I have a favorite bench at the park where I read on sunny days.",
        "I started composting food scraps on my balcony.",
        "I enjoy thunderstorm sounds and have a playlist for rainy days.",
        "I always tip 20% or more at restaurants.",
        "I have an old Polaroid camera that I use for special occasions.",
        "I keep a list of restaurants I want to try on Google Maps.",
        "I recently started oil painting and find it very relaxing.",
        "I prefer handwritten notes over digital ones for brainstorming.",
        "I schedule deep work blocks of 2 hours without interruptions.",
        "I have a monthly budget review session with Sarah.",
        "I enjoy watching documentaries about space and the ocean.",
        "I collect fridge magnets from places I've visited.",
        "I send handwritten birthday cards to close friends and family.",
        "I keep a separate reading log with ratings and brief reviews.",
        "I have a morning playlist that helps me get energized for the day.",
        "I prefer camping in national parks over staying in hotels.",
        "I always bring a book when I travel, even for short trips.",

        // More daily experiences (19 entries)
        "I tried a new Indian restaurant and the butter chicken was incredible.",
        "I fixed a bug in production at 2am and couldn't fall back asleep.",
        "I found a great park bench for reading near the waterfront.",
        "I learned to make espresso at home with a Breville machine.",
        "I reorganized my closet using the KonMari method.",
        "I replaced the battery in my old watch instead of buying a new one.",
        "I started tracking my mood in a daily journal app.",
        "I went to a flea market and found a vintage typewriter.",
        "I tried intermittent fasting for a month and felt more energetic.",
        "I started using a Kindle for reading on public transit.",
        "I made homemade pasta sauce with tomatoes from my garden.",
        "I signed up for a woodworking class at the community center.",
        "I discovered a shortcut through the park that saves 10 minutes.",
        "I cleaned out my garage and donated half the stuff.",
        "I bought a new pair of running shoes - Brooks Ghost 15.",
        "I tried bulletproof coffee and it kept me going until lunch.",
        "I organized my digital photos by year and location.",
        "I started using a paper planner alongside my digital calendar.",
        "I tried a sensory deprivation float tank and it was deeply relaxing.",

        // More people & conversations (19 entries)
        "My friend Mike is a sommelier and recommends great wines.",
        "I had a deep conversation with Sarah about where we want to live long-term.",
        "My dentist Dr. Kim says I need to floss more often.",
        "I caught up with my old professor Dr. Wang over video call.",
        "My barista at the corner cafe knows my order by heart.",
        "Sarah's friend Jenny recommended a great therapist.",
        "My accountant advised me to max out my Roth IRA contributions.",
        "I met an interesting data scientist named Raj at the tech meetup.",
        "My landlord agreed to fix the heating system before winter.",
        "I had lunch with my former colleague Anna who just started a company.",
        "My optometrist said my prescription hasn't changed this year.",
        "I helped my brother set up his first development environment.",
        "My physical therapist showed me new exercises for my knee.",
        "I talked to my financial advisor about rebalancing my portfolio.",
        "Sarah and I discussed getting a bigger apartment for the cat.",
        "My friend group is planning a camping trip for August.",
        "My teammate Chen built an amazing internal dashboard.",
        "I met a professional climber at the gym who gave me tips.",
        "My college friend Rachel moved to Berlin for a new job.",

        // More opinions & thoughts (19 entries)
        "I think pair programming is underrated for knowledge sharing.",
        "I believe morning exercise sets a positive tone for the day.",
        "I prefer smaller companies over large corporations for work culture.",
        "I think everyone should travel solo at least once in their life.",
        "I value consistency over intensity when building habits.",
        "I believe cooking at home is both healthier and more economical.",
        "I think reading fiction improves empathy and emotional intelligence.",
        "I prefer quality over quantity when it comes to friendships.",
        "I believe learning a musical instrument improves cognitive function.",
        "I think walking meetings are more productive than sitting ones.",
        "I prefer minimalist design in both software and living spaces.",
        "I believe in the power of compound interest for long-term wealth.",
        "I think journaling is one of the best self-improvement practices.",
        "I prefer electric bikes for city commuting over regular bikes.",
        "I believe sleep is the most important factor for productivity.",
        "I think microservices are overused for simple applications.",
        "I prefer functional programming style even in imperative languages.",
        "I believe code reviews are essential for team growth.",
        "I think analog hobbies are important for digital workers.",

        // More experiences & events (19 entries)
        "I went to a local art gallery opening and bought a small print.",
        "I completed a 30-day yoga challenge and felt much more flexible.",
        "I attended a whiskey tasting event and learned about single malts.",
        "I took a sunrise hike and the view from the peak was breathtaking.",
        "I tried my hand at watercolor painting during a weekend workshop.",
        "I went to a live comedy show and laughed until my stomach hurt.",
        "I participated in a tree planting event in the local forest.",
        "I attended a lecture on quantum computing at the university.",
        "I went stargazing at a dark sky reserve and saw the Milky Way.",
        "I tried escape rooms with friends and we solved it in 45 minutes.",
        "I visited a sake brewery and learned about the fermentation process.",
        "I went to a farmer's market and discovered amazing local honey.",
        "I attended an outdoor concert in the park and it was magical.",
        "I took a cooking class focused on making fresh pasta shapes.",
        "I went whale watching and spotted a humpback whale breaching.",
        "I tried hot yoga for the first time and it was intense.",
        "I attended a book signing by my favorite sci-fi author.",
        "I went to a vintage car show and saw a 1967 Mustang.",
        "I tried cold water swimming in the lake and felt invigorated.",

        // More tech & projects (19 entries)
        "I set up a self-hosted RSS reader using Miniflux.",
        "I migrated my personal email to Fastmail for better privacy.",
        "I wrote a script to automate downloading podcast episodes.",
        "I configured Wireguard VPN on my home server for secure access.",
        "I built a weather station with Arduino sensors on my balcony.",
        "I created a custom Alfred workflow for quick note-taking.",
        "I set up automated backups to Backblaze B2 cloud storage.",
        "I wrote a small Rust CLI to manage my dotfiles across machines.",
        "I experimented with SQLite as a primary database for a side project.",
        "I set up a Minecraft server for friends on my home server.",
        "I built a Telegram bot that sends me daily weather forecasts.",
        "I wrote unit tests for our legacy codebase and found three bugs.",
        "I contributed a bug fix to the DuckDB project on GitHub.",
        "I set up a local development environment using Docker Compose.",
        "I experimented with vector databases for semantic search.",
        "I built a personal finance tracker using Python and Pandas.",
        "I automated my plant watering system with a Raspberry Pi.",
        "I wrote a browser extension that blocks distracting websites.",
        "I set up a local Kubernetes cluster using k3s for learning.",

        // More memories & reflections (19 entries)
        "I remember the first time I saw the ocean as a child in Oregon.",
        "My first programming project was a calculator app in high school.",
        "I still remember the taste of my grandmother's cinnamon rolls.",
        "The day I got my first job offer was one of the happiest days.",
        "I remember staying up all night to finish my senior thesis.",
        "My first concert was Green Day when I was 14 years old.",
        "I remember learning to ride a bike in the backyard.",
        "The first book that really changed my perspective was Sapiens.",
        "I remember my first day of college feeling both excited and nervous.",
        "My first attempt at cooking was scrambled eggs that turned out rubbery.",
        "I remember the relief of passing my driving test on the first try.",
        "The first time I deployed code to production I was terrified.",
        "I remember building a tree house with my dad when I was 10.",
        "My first international trip was to Mexico with my family.",
        "I remember the excitement of getting my first mechanical keyboard.",
        "The first time I saw snow was during a trip to Colorado.",
        "I remember adopting Mochi from the shelter - she was so tiny.",
        "My first apartment was a tiny studio but I loved the independence.",
        "I remember Sarah laughing at my terrible first attempt at sushi.",

        // More plans & goals (19 entries)
        "I want to learn woodworking and build my own desk.",
        "I plan to read 36 books this year, tracking progress monthly.",
        "I want to visit every national park in the Pacific Northwest.",
        "I'm planning to upgrade my home network to Wi-Fi 7.",
        "I want to learn to sail and eventually buy a small sailboat.",
        "I plan to complete a Spartan Race next summer.",
        "I want to build a mobile app for tracking hiking trails.",
        "I'm considering learning Spanish as my third language.",
        "I want to start a YouTube channel about home lab setups.",
        "I plan to run an ultramarathon within the next two years.",
        "I want to visit the Christmas markets in Vienna and Prague.",
        "I'm planning to build a home library with floor-to-ceiling shelves.",
        "I want to learn beekeeping and have a small hive on the roof.",
        "I plan to mentor more junior developers through open source.",
        "I want to do a digital nomad stint in Southeast Asia.",
        "I'm planning to take an advanced photography course.",
        "I want to learn ceramics and make my own dinnerware.",
        "I plan to set up solar panels on my future home.",
        "I want to participate in a multi-day hiking expedition.",

        // More misc (76 entries to reach 500)
        "I prefer earl grey tea in the afternoon with a splash of milk.",
        "I have a collection of interesting rocks from hikes.",
        "I always carry a small notebook and pen in my pocket.",
        "I prefer audiobooks for non-fiction and physical books for fiction.",
        "I have a lucky charm - a coin my grandfather gave me.",
        "I enjoy the sound of rain on the roof while working.",
        "I rotate between three pairs of headphones depending on the activity.",
        "I keep a small first-aid kit in my backpack at all times.",
        "I enjoy the ritual of making tea as much as drinking it.",
        "I have a favorite mug that I use every morning - it has a cat on it.",
        "I prefer to sit facing the door in restaurants.",
        "I always double-check that the stove is off before leaving home.",
        "I have a Spotify playlist for every mood and activity.",
        "I prefer non-fiction during the week and fiction on weekends.",
        "I keep my desk clean and organized - a clear desk helps me think.",
        "I enjoy the smell of freshly cut grass in the spring.",
        "I have a shelf dedicated to board games for game nights.",
        "I prefer to walk rather than drive for distances under 2 miles.",
        "I always pack my own lunch for work to save money.",
        "I have a favorite hoodie that I wear while coding at home.",
        "I enjoy watching the sunset from the rooftop of my building.",
        "I keep a list of interesting words and their meanings.",
        "I prefer mechanical pencils over regular pencils.",
        "I always arrive 5-10 minutes early to appointments.",
        "I have a ritual of listening to jazz while cooking dinner.",
        "I prefer sparkling water over still water with meals.",
        "I keep my phone charger on the left side of the bed.",
        "I enjoy organizing things by category and label.",
        "I prefer cotton shirts over synthetic fabrics.",
        "I have a favorite hiking trail that takes about 3 hours round trip.",
        "I always read product reviews before making purchases.",
        "I enjoy watching time-lapse videos of cityscapes.",
        "I prefer to shower in the morning rather than at night.",
        "I keep a spare jacket at the office for unexpected cold weather.",
        "I enjoy the sound of a vinyl record crackling before the music starts.",
        "I prefer dark mode on all my devices and applications.",
        "I have a collection of interesting tea varieties from different countries.",
        "I always back up my phone before updating the operating system.",
        "I enjoy sketching floor plans for my dream house.",
        "I prefer aisle seats on long flights for easier movement.",
        "I have a favorite pen - a Pilot G2 07.",
        "I keep my wallet minimal with only essential cards.",
        "I enjoy the quiet of early morning before the city wakes up.",
        "I prefer to meal plan for the week to avoid food waste.",
        "I have a dedicated drawer for cables and tech accessories.",
        "I always test my code locally before pushing to the remote repo.",
        "I enjoy visiting used bookstores and discovering hidden gems.",
        "I prefer gas stoves over electric for cooking precision.",
        "I keep an emergency kit in the closet with flashlights and batteries.",
        "I enjoy the feeling of finishing a difficult coding problem.",
        "I prefer warm lighting in the evening and cool lighting during the day.",
        "I have a favorite spot at the library near the big window.",
        "I always clean the kitchen before going to bed.",
        "I enjoy tracking flights on Flightradar24 when I hear planes.",
        "I prefer loose-leaf tea over tea bags for better flavor.",
        "I keep a pair of binoculars for birdwatching from my balcony.",
        "I enjoy the meditative aspect of hand-grinding coffee beans.",
    ]

    static let queries: [String] = [
        "What are Alice's hobbies?",
        "Tell me about the trip to Japan",
        "What is my morning routine?",
        "Do I have any pets?",
        "What programming languages do I use?",
        "Tell me about my partner",
        "What kind of food do I like?",
        "Where do I work?",
        "What are my fitness goals?",
        "Do I have any siblings?",
        "What is my favorite music?",
        "Tell me about my cat",
        "What books am I reading?",
        "Where do I live?",
        "What is my exercise routine?",
        "Tell me about my travel plans",
        "What do I do for fun on weekends?",
        "Who is Bob?",
        "What is my diet like?",
        "Tell me about my home office setup",
        "Do I have any allergies?",
        "What tech gadgets do I use?",
        "Who are my closest friends?",
        "What is my coffee preference?",
        "Tell me about my career",
        "What are my financial goals?",
        "Do I volunteer anywhere?",
        "What is my sleep schedule?",
        "Tell me about my cooking skills",
        "What certifications do I have?",
        "What TV shows do I watch?",
        "Where did I go to school?",
        "What is my favorite restaurant?",
        "Do I play any sports?",
        "Tell me about my side projects",
        "What is my favorite season?",
        "Who is Sarah?",
        "What do I collect?",
        "Tell me about my childhood memories",
        "What is my work schedule?",
        "Do I have a home server?",
        "What is my favorite movie genre?",
        "Tell me about my health concerns",
        "What apps do I use daily?",
        "Who is my manager?",
        "What are my weekend plans?",
        "Tell me about my apartment",
        "What is my commute like?",
        "Do I play any musical instruments?",
        "What are my environmental habits?",
        "Tell me about scuba diving",
        "What kind of keyboard do I use?",
        "Who lives in Tokyo?",
        "What meditation do I practice?",
        "Tell me about the hackathon",
        "What is my blood type?",
        "How do I manage my tasks?",
        "Tell me about my grandmother",
        "What photography do I enjoy?",
        "Do I drink alcohol?",
        "What is my shoe size?",
        "Tell me about my investment strategy",
        "Who is Priya?",
        "What podcasts do I listen to?",
        "Tell me about my balcony garden",
        "What is my typing speed?",
        "Do I have any phobias?",
        "What conferences have I attended?",
        "Tell me about my neighbor David",
        "What board games do I play?",
        "Where do I want to travel next?",
        "Tell me about my sourdough baking",
        "What operating system do I use?",
        "Who is my pen pal?",
        "What is my favorite breakfast?",
        "Tell me about the production outage",
        "Do I use a standing desk?",
        "What charity work do I do?",
        "Tell me about chess club",
        "What supplements do I take?",
        "Who is Carlos?",
        "What is my evening routine?",
        "Tell me about my anniversary",
        "What smart home devices do I have?",
        "Do I do any art?",
        "What is my work-life balance like?",
        "Tell me about my reading habits",
        "What did I learn during pandemic?",
        "Who are The Wanderers?",
        "What is my skincare routine?",
        "Tell me about my uncle's bookshop",
        "What do I do for stress relief?",
        "Who is James and what happened recently?",
        "What is my nap schedule?",
        "Tell me about my email habits",
        "What cold weather gear do I have?",
        "Do I have a dream journal?",
        "What wine regions have I visited?",
        "Tell me about my map collection",
        "What is my favorite chocolate?",
    ]
}
