// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(memme_ffiFFI)
import memme_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_memme_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_memme_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureMemmeFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * The main MemMe memory store, exposed as a UniFFI Object.
 *
 * For iOS / Android, create with `new_with_http_client` and supply a native
 * HTTP client (URLSession / OkHttp). For testing, use `new_mock`.
 */
public protocol MemoryStoreProtocol: AnyObject, Sendable {
    
    func add(content: String, userId: String, agentId: String?, runId: String?, metadata: String?) throws  -> MemoryResult
    
    /**
     * Extract knowledge-graph entities and relationships via LLM.
     */
    func addGraph(text: String, userId: String, llmModel: String?, llmBaseUrl: String?) throws  -> GraphSearchResult
    
    /**
     * Smart add: extract facts via LLM. Uses the LLM configured at construction time.
     * Optional `llm_model` / `llm_base_url` override the defaults.
     */
    func addSmart(text: String, userId: String, llmModel: String?, llmBaseUrl: String?, agentId: String?, runId: String?, metadata: String?) throws  -> [MemoryResult]
    
    /**
     * Smart add from chat messages.
     */
    func addSmartMessages(messages: [ChatMessage], userId: String, llmModel: String?, llmBaseUrl: String?, agentId: String?, runId: String?, metadata: String?) throws  -> [MemoryResult]
    
    func delete(id: String) throws 
    
    func deleteAll(userId: String, agentId: String?, runId: String?) throws  -> UInt64
    
    func get(id: String) throws  -> MemoryResult?
    
    func history(memoryId: String) throws  -> [HistoryRecord]
    
    func hybridSearch(query: String, userId: String, agentId: String?, runId: String?, limit: UInt32?, vectorWeight: Double?, ftsWeight: Double?) throws  -> [MemoryResult]
    
    func list(userId: String, agentId: String?, runId: String?, limit: UInt32?) throws  -> [MemoryResult]
    
    func memoryFrequency(userId: String, granularity: String, limit: UInt32) throws  -> [TimeBucket]
    
    func rebuildFtsIndex() throws 
    
    func reset() throws 
    
    func search(query: String, userId: String, agentId: String?, runId: String?, limit: UInt32?, threshold: Float?) throws  -> [MemoryResult]
    
    func searchGraph(query: String, userId: String, depth: UInt32?) throws  -> GraphSearchResult
    
    func topEntities(userId: String, limit: UInt32) throws  -> [EntityStat]
    
    func update(id: String, content: String) throws  -> MemoryResult
    
    func userStats(userId: String) throws  -> UserStats
    
}
/**
 * The main MemMe memory store, exposed as a UniFFI Object.
 *
 * For iOS / Android, create with `new_with_http_client` and supply a native
 * HTTP client (URLSession / OkHttp). For testing, use `new_mock`.
 */
open class MemoryStore: MemoryStoreProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_memme_ffi_fn_clone_memorystore(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_memme_ffi_fn_free_memorystore(pointer, $0) }
    }

    
    /**
     * Create a MemoryStore with a mock embedder (useful for testing, no API needed).
     */
public static func newMock(dbPath: String, dims: UInt32)throws  -> MemoryStore  {
    return try  FfiConverterTypeMemoryStore_lift(try rustCallWithError(FfiConverterTypeMemmeError_lift) {
    uniffi_memme_ffi_fn_constructor_memorystore_new_mock(
        FfiConverterString.lower(dbPath),
        FfiConverterUInt32.lower(dims),$0
    )
})
}
    
    /**
     * Create a MemoryStore with an HTTP client callback for OpenAI-compatible APIs.
     *
     * The host app implements `HttpClient` (e.g. URLSession on iOS, OkHttp on Android).
     * Both embedding and LLM calls are routed through this single callback.
     *
     * Note: `http_client` is `Box<dyn HttpClient>` — UniFFI callback interfaces
     * use `Box`, not `Arc`, on the foreign side.
     */
public static func newWithHttpClient(dbPath: String, httpClient: HttpClient, apiKey: String, embeddingModel: String?, embeddingDims: UInt32?, llmBaseUrl: String?)throws  -> MemoryStore  {
    return try  FfiConverterTypeMemoryStore_lift(try rustCallWithError(FfiConverterTypeMemmeError_lift) {
    uniffi_memme_ffi_fn_constructor_memorystore_new_with_http_client(
        FfiConverterString.lower(dbPath),
        FfiConverterCallbackInterfaceHttpClient_lower(httpClient),
        FfiConverterString.lower(apiKey),
        FfiConverterOptionString.lower(embeddingModel),
        FfiConverterOptionUInt32.lower(embeddingDims),
        FfiConverterOptionString.lower(llmBaseUrl),$0
    )
})
}
    

    
open func add(content: String, userId: String, agentId: String?, runId: String?, metadata: String?)throws  -> MemoryResult  {
    return try  FfiConverterTypeMemoryResult_lift(try rustCallWithError(FfiConverterTypeMemmeError_lift) {
    uniffi_memme_ffi_fn_method_memorystore_add(self.uniffiClonePointer(),
        FfiConverterString.lower(content),
        FfiConverterString.lower(userId),
        FfiConverterOptionString.lower(agentId),
        FfiConverterOptionString.lower(runId),
        FfiConverterOptionString.lower(metadata),$0
    )
})
}
    
    /**
     * Extract knowledge-graph entities and relationships via LLM.
     */
open func addGraph(text: String, userId: String, llmModel: String?, llmBaseUrl: String?)throws  -> GraphSearchResult  {
    return try  FfiConverterTypeGraphSearchResult_lift(try rustCallWithError(FfiConverterTypeMemmeError_lift) {
    uniffi_memme_ffi_fn_method_memorystore_add_graph(self.uniffiClonePointer(),
        FfiConverterString.lower(text),
        FfiConverterString.lower(userId),
        FfiConverterOptionString.lower(llmModel),
        FfiConverterOptionString.lower(llmBaseUrl),$0
    )
})
}
    
    /**
     * Smart add: extract facts via LLM. Uses the LLM configured at construction time.
     * Optional `llm_model` / `llm_base_url` override the defaults.
     */
open func addSmart(text: String, userId: String, llmModel: String?, llmBaseUrl: String?, agentId: String?, runId: String?, metadata: String?)throws  -> [MemoryResult]  {
    return try  FfiConverterSequenceTypeMemoryResult.lift(try rustCallWithError(FfiConverterTypeMemmeError_lift) {
    uniffi_memme_ffi_fn_method_memorystore_add_smart(self.uniffiClonePointer(),
        FfiConverterString.lower(text),
        FfiConverterString.lower(userId),
        FfiConverterOptionString.lower(llmModel),
        FfiConverterOptionString.lower(llmBaseUrl),
        FfiConverterOptionString.lower(agentId),
        FfiConverterOptionString.lower(runId),
        FfiConverterOptionString.lower(metadata),$0
    )
})
}
    
    /**
     * Smart add from chat messages.
     */
open func addSmartMessages(messages: [ChatMessage], userId: String, llmModel: String?, llmBaseUrl: String?, agentId: String?, runId: String?, metadata: String?)throws  -> [MemoryResult]  {
    return try  FfiConverterSequenceTypeMemoryResult.lift(try rustCallWithError(FfiConverterTypeMemmeError_lift) {
    uniffi_memme_ffi_fn_method_memorystore_add_smart_messages(self.uniffiClonePointer(),
        FfiConverterSequenceTypeChatMessage.lower(messages),
        FfiConverterString.lower(userId),
        FfiConverterOptionString.lower(llmModel),
        FfiConverterOptionString.lower(llmBaseUrl),
        FfiConverterOptionString.lower(agentId),
        FfiConverterOptionString.lower(runId),
        FfiConverterOptionString.lower(metadata),$0
    )
})
}
    
open func delete(id: String)throws   {try rustCallWithError(FfiConverterTypeMemmeError_lift) {
    uniffi_memme_ffi_fn_method_memorystore_delete(self.uniffiClonePointer(),
        FfiConverterString.lower(id),$0
    )
}
}
    
open func deleteAll(userId: String, agentId: String?, runId: String?)throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeMemmeError_lift) {
    uniffi_memme_ffi_fn_method_memorystore_delete_all(self.uniffiClonePointer(),
        FfiConverterString.lower(userId),
        FfiConverterOptionString.lower(agentId),
        FfiConverterOptionString.lower(runId),$0
    )
})
}
    
open func get(id: String)throws  -> MemoryResult?  {
    return try  FfiConverterOptionTypeMemoryResult.lift(try rustCallWithError(FfiConverterTypeMemmeError_lift) {
    uniffi_memme_ffi_fn_method_memorystore_get(self.uniffiClonePointer(),
        FfiConverterString.lower(id),$0
    )
})
}
    
open func history(memoryId: String)throws  -> [HistoryRecord]  {
    return try  FfiConverterSequenceTypeHistoryRecord.lift(try rustCallWithError(FfiConverterTypeMemmeError_lift) {
    uniffi_memme_ffi_fn_method_memorystore_history(self.uniffiClonePointer(),
        FfiConverterString.lower(memoryId),$0
    )
})
}
    
open func hybridSearch(query: String, userId: String, agentId: String?, runId: String?, limit: UInt32?, vectorWeight: Double?, ftsWeight: Double?)throws  -> [MemoryResult]  {
    return try  FfiConverterSequenceTypeMemoryResult.lift(try rustCallWithError(FfiConverterTypeMemmeError_lift) {
    uniffi_memme_ffi_fn_method_memorystore_hybrid_search(self.uniffiClonePointer(),
        FfiConverterString.lower(query),
        FfiConverterString.lower(userId),
        FfiConverterOptionString.lower(agentId),
        FfiConverterOptionString.lower(runId),
        FfiConverterOptionUInt32.lower(limit),
        FfiConverterOptionDouble.lower(vectorWeight),
        FfiConverterOptionDouble.lower(ftsWeight),$0
    )
})
}
    
open func list(userId: String, agentId: String?, runId: String?, limit: UInt32?)throws  -> [MemoryResult]  {
    return try  FfiConverterSequenceTypeMemoryResult.lift(try rustCallWithError(FfiConverterTypeMemmeError_lift) {
    uniffi_memme_ffi_fn_method_memorystore_list(self.uniffiClonePointer(),
        FfiConverterString.lower(userId),
        FfiConverterOptionString.lower(agentId),
        FfiConverterOptionString.lower(runId),
        FfiConverterOptionUInt32.lower(limit),$0
    )
})
}
    
open func memoryFrequency(userId: String, granularity: String, limit: UInt32)throws  -> [TimeBucket]  {
    return try  FfiConverterSequenceTypeTimeBucket.lift(try rustCallWithError(FfiConverterTypeMemmeError_lift) {
    uniffi_memme_ffi_fn_method_memorystore_memory_frequency(self.uniffiClonePointer(),
        FfiConverterString.lower(userId),
        FfiConverterString.lower(granularity),
        FfiConverterUInt32.lower(limit),$0
    )
})
}
    
open func rebuildFtsIndex()throws   {try rustCallWithError(FfiConverterTypeMemmeError_lift) {
    uniffi_memme_ffi_fn_method_memorystore_rebuild_fts_index(self.uniffiClonePointer(),$0
    )
}
}
    
open func reset()throws   {try rustCallWithError(FfiConverterTypeMemmeError_lift) {
    uniffi_memme_ffi_fn_method_memorystore_reset(self.uniffiClonePointer(),$0
    )
}
}
    
open func search(query: String, userId: String, agentId: String?, runId: String?, limit: UInt32?, threshold: Float?)throws  -> [MemoryResult]  {
    return try  FfiConverterSequenceTypeMemoryResult.lift(try rustCallWithError(FfiConverterTypeMemmeError_lift) {
    uniffi_memme_ffi_fn_method_memorystore_search(self.uniffiClonePointer(),
        FfiConverterString.lower(query),
        FfiConverterString.lower(userId),
        FfiConverterOptionString.lower(agentId),
        FfiConverterOptionString.lower(runId),
        FfiConverterOptionUInt32.lower(limit),
        FfiConverterOptionFloat.lower(threshold),$0
    )
})
}
    
open func searchGraph(query: String, userId: String, depth: UInt32?)throws  -> GraphSearchResult  {
    return try  FfiConverterTypeGraphSearchResult_lift(try rustCallWithError(FfiConverterTypeMemmeError_lift) {
    uniffi_memme_ffi_fn_method_memorystore_search_graph(self.uniffiClonePointer(),
        FfiConverterString.lower(query),
        FfiConverterString.lower(userId),
        FfiConverterOptionUInt32.lower(depth),$0
    )
})
}
    
open func topEntities(userId: String, limit: UInt32)throws  -> [EntityStat]  {
    return try  FfiConverterSequenceTypeEntityStat.lift(try rustCallWithError(FfiConverterTypeMemmeError_lift) {
    uniffi_memme_ffi_fn_method_memorystore_top_entities(self.uniffiClonePointer(),
        FfiConverterString.lower(userId),
        FfiConverterUInt32.lower(limit),$0
    )
})
}
    
open func update(id: String, content: String)throws  -> MemoryResult  {
    return try  FfiConverterTypeMemoryResult_lift(try rustCallWithError(FfiConverterTypeMemmeError_lift) {
    uniffi_memme_ffi_fn_method_memorystore_update(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterString.lower(content),$0
    )
})
}
    
open func userStats(userId: String)throws  -> UserStats  {
    return try  FfiConverterTypeUserStats_lift(try rustCallWithError(FfiConverterTypeMemmeError_lift) {
    uniffi_memme_ffi_fn_method_memorystore_user_stats(self.uniffiClonePointer(),
        FfiConverterString.lower(userId),$0
    )
})
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMemoryStore: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = MemoryStore

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> MemoryStore {
        return MemoryStore(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: MemoryStore) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MemoryStore {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: MemoryStore, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMemoryStore_lift(_ pointer: UnsafeMutableRawPointer) throws -> MemoryStore {
    return try FfiConverterTypeMemoryStore.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMemoryStore_lower(_ value: MemoryStore) -> UnsafeMutableRawPointer {
    return FfiConverterTypeMemoryStore.lower(value)
}




public struct ChatMessage {
    public var role: String
    public var content: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(role: String, content: String) {
        self.role = role
        self.content = content
    }
}

#if compiler(>=6)
extension ChatMessage: Sendable {}
#endif


extension ChatMessage: Equatable, Hashable {
    public static func ==(lhs: ChatMessage, rhs: ChatMessage) -> Bool {
        if lhs.role != rhs.role {
            return false
        }
        if lhs.content != rhs.content {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(role)
        hasher.combine(content)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeChatMessage: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ChatMessage {
        return
            try ChatMessage(
                role: FfiConverterString.read(from: &buf), 
                content: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: ChatMessage, into buf: inout [UInt8]) {
        FfiConverterString.write(value.role, into: &buf)
        FfiConverterString.write(value.content, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChatMessage_lift(_ buf: RustBuffer) throws -> ChatMessage {
    return try FfiConverterTypeChatMessage.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChatMessage_lower(_ value: ChatMessage) -> RustBuffer {
    return FfiConverterTypeChatMessage.lower(value)
}


public struct Entity {
    public var id: String
    public var name: String
    public var entityType: String?
    public var userId: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, name: String, entityType: String?, userId: String) {
        self.id = id
        self.name = name
        self.entityType = entityType
        self.userId = userId
    }
}

#if compiler(>=6)
extension Entity: Sendable {}
#endif


extension Entity: Equatable, Hashable {
    public static func ==(lhs: Entity, rhs: Entity) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.name != rhs.name {
            return false
        }
        if lhs.entityType != rhs.entityType {
            return false
        }
        if lhs.userId != rhs.userId {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(name)
        hasher.combine(entityType)
        hasher.combine(userId)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEntity: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Entity {
        return
            try Entity(
                id: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                entityType: FfiConverterOptionString.read(from: &buf), 
                userId: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Entity, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterOptionString.write(value.entityType, into: &buf)
        FfiConverterString.write(value.userId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEntity_lift(_ buf: RustBuffer) throws -> Entity {
    return try FfiConverterTypeEntity.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEntity_lower(_ value: Entity) -> RustBuffer {
    return FfiConverterTypeEntity.lower(value)
}


public struct EntityStat {
    public var name: String
    public var entityType: String?
    public var relationshipCount: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, entityType: String?, relationshipCount: UInt64) {
        self.name = name
        self.entityType = entityType
        self.relationshipCount = relationshipCount
    }
}

#if compiler(>=6)
extension EntityStat: Sendable {}
#endif


extension EntityStat: Equatable, Hashable {
    public static func ==(lhs: EntityStat, rhs: EntityStat) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.entityType != rhs.entityType {
            return false
        }
        if lhs.relationshipCount != rhs.relationshipCount {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(entityType)
        hasher.combine(relationshipCount)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEntityStat: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EntityStat {
        return
            try EntityStat(
                name: FfiConverterString.read(from: &buf), 
                entityType: FfiConverterOptionString.read(from: &buf), 
                relationshipCount: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: EntityStat, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterOptionString.write(value.entityType, into: &buf)
        FfiConverterUInt64.write(value.relationshipCount, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEntityStat_lift(_ buf: RustBuffer) throws -> EntityStat {
    return try FfiConverterTypeEntityStat.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEntityStat_lower(_ value: EntityStat) -> RustBuffer {
    return FfiConverterTypeEntityStat.lower(value)
}


public struct GraphRelation {
    public var id: String
    public var source: String
    public var sourceId: String
    public var target: String
    public var targetId: String
    public var relationType: String
    public var userId: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, source: String, sourceId: String, target: String, targetId: String, relationType: String, userId: String) {
        self.id = id
        self.source = source
        self.sourceId = sourceId
        self.target = target
        self.targetId = targetId
        self.relationType = relationType
        self.userId = userId
    }
}

#if compiler(>=6)
extension GraphRelation: Sendable {}
#endif


extension GraphRelation: Equatable, Hashable {
    public static func ==(lhs: GraphRelation, rhs: GraphRelation) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.source != rhs.source {
            return false
        }
        if lhs.sourceId != rhs.sourceId {
            return false
        }
        if lhs.target != rhs.target {
            return false
        }
        if lhs.targetId != rhs.targetId {
            return false
        }
        if lhs.relationType != rhs.relationType {
            return false
        }
        if lhs.userId != rhs.userId {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(source)
        hasher.combine(sourceId)
        hasher.combine(target)
        hasher.combine(targetId)
        hasher.combine(relationType)
        hasher.combine(userId)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGraphRelation: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GraphRelation {
        return
            try GraphRelation(
                id: FfiConverterString.read(from: &buf), 
                source: FfiConverterString.read(from: &buf), 
                sourceId: FfiConverterString.read(from: &buf), 
                target: FfiConverterString.read(from: &buf), 
                targetId: FfiConverterString.read(from: &buf), 
                relationType: FfiConverterString.read(from: &buf), 
                userId: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: GraphRelation, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.source, into: &buf)
        FfiConverterString.write(value.sourceId, into: &buf)
        FfiConverterString.write(value.target, into: &buf)
        FfiConverterString.write(value.targetId, into: &buf)
        FfiConverterString.write(value.relationType, into: &buf)
        FfiConverterString.write(value.userId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGraphRelation_lift(_ buf: RustBuffer) throws -> GraphRelation {
    return try FfiConverterTypeGraphRelation.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGraphRelation_lower(_ value: GraphRelation) -> RustBuffer {
    return FfiConverterTypeGraphRelation.lower(value)
}


public struct GraphSearchResult {
    public var entities: [Entity]
    public var relations: [GraphRelation]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(entities: [Entity], relations: [GraphRelation]) {
        self.entities = entities
        self.relations = relations
    }
}

#if compiler(>=6)
extension GraphSearchResult: Sendable {}
#endif


extension GraphSearchResult: Equatable, Hashable {
    public static func ==(lhs: GraphSearchResult, rhs: GraphSearchResult) -> Bool {
        if lhs.entities != rhs.entities {
            return false
        }
        if lhs.relations != rhs.relations {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(entities)
        hasher.combine(relations)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGraphSearchResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GraphSearchResult {
        return
            try GraphSearchResult(
                entities: FfiConverterSequenceTypeEntity.read(from: &buf), 
                relations: FfiConverterSequenceTypeGraphRelation.read(from: &buf)
        )
    }

    public static func write(_ value: GraphSearchResult, into buf: inout [UInt8]) {
        FfiConverterSequenceTypeEntity.write(value.entities, into: &buf)
        FfiConverterSequenceTypeGraphRelation.write(value.relations, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGraphSearchResult_lift(_ buf: RustBuffer) throws -> GraphSearchResult {
    return try FfiConverterTypeGraphSearchResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGraphSearchResult_lower(_ value: GraphSearchResult) -> RustBuffer {
    return FfiConverterTypeGraphSearchResult.lower(value)
}


public struct HistoryRecord {
    public var id: String
    public var memoryId: String
    public var oldMemory: String?
    public var newMemory: String
    public var event: String
    public var createdAt: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, memoryId: String, oldMemory: String?, newMemory: String, event: String, createdAt: String) {
        self.id = id
        self.memoryId = memoryId
        self.oldMemory = oldMemory
        self.newMemory = newMemory
        self.event = event
        self.createdAt = createdAt
    }
}

#if compiler(>=6)
extension HistoryRecord: Sendable {}
#endif


extension HistoryRecord: Equatable, Hashable {
    public static func ==(lhs: HistoryRecord, rhs: HistoryRecord) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.memoryId != rhs.memoryId {
            return false
        }
        if lhs.oldMemory != rhs.oldMemory {
            return false
        }
        if lhs.newMemory != rhs.newMemory {
            return false
        }
        if lhs.event != rhs.event {
            return false
        }
        if lhs.createdAt != rhs.createdAt {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(memoryId)
        hasher.combine(oldMemory)
        hasher.combine(newMemory)
        hasher.combine(event)
        hasher.combine(createdAt)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHistoryRecord: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HistoryRecord {
        return
            try HistoryRecord(
                id: FfiConverterString.read(from: &buf), 
                memoryId: FfiConverterString.read(from: &buf), 
                oldMemory: FfiConverterOptionString.read(from: &buf), 
                newMemory: FfiConverterString.read(from: &buf), 
                event: FfiConverterString.read(from: &buf), 
                createdAt: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: HistoryRecord, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.memoryId, into: &buf)
        FfiConverterOptionString.write(value.oldMemory, into: &buf)
        FfiConverterString.write(value.newMemory, into: &buf)
        FfiConverterString.write(value.event, into: &buf)
        FfiConverterString.write(value.createdAt, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHistoryRecord_lift(_ buf: RustBuffer) throws -> HistoryRecord {
    return try FfiConverterTypeHistoryRecord.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHistoryRecord_lower(_ value: HistoryRecord) -> RustBuffer {
    return FfiConverterTypeHistoryRecord.lower(value)
}


public struct MemoryResult {
    public var id: String
    public var content: String
    public var userId: String
    public var agentId: String?
    public var appId: String?
    public var runId: String?
    public var score: Float?
    public var createdAt: String
    public var updatedAt: String
    public var metadata: String?
    public var importance: Float?
    public var accessCount: UInt32?
    public var immutable: Bool
    public var expirationDate: String?
    public var categories: [String]?
    public var retention: Float?
    public var stability: Float?
    public var eventTime: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, content: String, userId: String, agentId: String?, appId: String?, runId: String?, score: Float?, createdAt: String, updatedAt: String, metadata: String?, importance: Float?, accessCount: UInt32?, immutable: Bool, expirationDate: String?, categories: [String]?, retention: Float?, stability: Float?, eventTime: String?) {
        self.id = id
        self.content = content
        self.userId = userId
        self.agentId = agentId
        self.appId = appId
        self.runId = runId
        self.score = score
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.metadata = metadata
        self.importance = importance
        self.accessCount = accessCount
        self.immutable = immutable
        self.expirationDate = expirationDate
        self.categories = categories
        self.retention = retention
        self.stability = stability
        self.eventTime = eventTime
    }
}

#if compiler(>=6)
extension MemoryResult: Sendable {}
#endif


extension MemoryResult: Equatable, Hashable {
    public static func ==(lhs: MemoryResult, rhs: MemoryResult) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.content != rhs.content {
            return false
        }
        if lhs.userId != rhs.userId {
            return false
        }
        if lhs.agentId != rhs.agentId {
            return false
        }
        if lhs.appId != rhs.appId {
            return false
        }
        if lhs.runId != rhs.runId {
            return false
        }
        if lhs.score != rhs.score {
            return false
        }
        if lhs.createdAt != rhs.createdAt {
            return false
        }
        if lhs.updatedAt != rhs.updatedAt {
            return false
        }
        if lhs.metadata != rhs.metadata {
            return false
        }
        if lhs.importance != rhs.importance {
            return false
        }
        if lhs.accessCount != rhs.accessCount {
            return false
        }
        if lhs.immutable != rhs.immutable {
            return false
        }
        if lhs.expirationDate != rhs.expirationDate {
            return false
        }
        if lhs.categories != rhs.categories {
            return false
        }
        if lhs.retention != rhs.retention {
            return false
        }
        if lhs.stability != rhs.stability {
            return false
        }
        if lhs.eventTime != rhs.eventTime {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(content)
        hasher.combine(userId)
        hasher.combine(agentId)
        hasher.combine(appId)
        hasher.combine(runId)
        hasher.combine(score)
        hasher.combine(createdAt)
        hasher.combine(updatedAt)
        hasher.combine(metadata)
        hasher.combine(importance)
        hasher.combine(accessCount)
        hasher.combine(immutable)
        hasher.combine(expirationDate)
        hasher.combine(categories)
        hasher.combine(retention)
        hasher.combine(stability)
        hasher.combine(eventTime)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMemoryResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MemoryResult {
        return
            try MemoryResult(
                id: FfiConverterString.read(from: &buf), 
                content: FfiConverterString.read(from: &buf), 
                userId: FfiConverterString.read(from: &buf), 
                agentId: FfiConverterOptionString.read(from: &buf), 
                appId: FfiConverterOptionString.read(from: &buf), 
                runId: FfiConverterOptionString.read(from: &buf), 
                score: FfiConverterOptionFloat.read(from: &buf), 
                createdAt: FfiConverterString.read(from: &buf), 
                updatedAt: FfiConverterString.read(from: &buf), 
                metadata: FfiConverterOptionString.read(from: &buf), 
                importance: FfiConverterOptionFloat.read(from: &buf), 
                accessCount: FfiConverterOptionUInt32.read(from: &buf), 
                immutable: FfiConverterBool.read(from: &buf), 
                expirationDate: FfiConverterOptionString.read(from: &buf), 
                categories: FfiConverterOptionSequenceString.read(from: &buf), 
                retention: FfiConverterOptionFloat.read(from: &buf), 
                stability: FfiConverterOptionFloat.read(from: &buf), 
                eventTime: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: MemoryResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.content, into: &buf)
        FfiConverterString.write(value.userId, into: &buf)
        FfiConverterOptionString.write(value.agentId, into: &buf)
        FfiConverterOptionString.write(value.appId, into: &buf)
        FfiConverterOptionString.write(value.runId, into: &buf)
        FfiConverterOptionFloat.write(value.score, into: &buf)
        FfiConverterString.write(value.createdAt, into: &buf)
        FfiConverterString.write(value.updatedAt, into: &buf)
        FfiConverterOptionString.write(value.metadata, into: &buf)
        FfiConverterOptionFloat.write(value.importance, into: &buf)
        FfiConverterOptionUInt32.write(value.accessCount, into: &buf)
        FfiConverterBool.write(value.immutable, into: &buf)
        FfiConverterOptionString.write(value.expirationDate, into: &buf)
        FfiConverterOptionSequenceString.write(value.categories, into: &buf)
        FfiConverterOptionFloat.write(value.retention, into: &buf)
        FfiConverterOptionFloat.write(value.stability, into: &buf)
        FfiConverterOptionString.write(value.eventTime, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMemoryResult_lift(_ buf: RustBuffer) throws -> MemoryResult {
    return try FfiConverterTypeMemoryResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMemoryResult_lower(_ value: MemoryResult) -> RustBuffer {
    return FfiConverterTypeMemoryResult.lower(value)
}


public struct TimeBucket {
    public var period: String
    public var count: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(period: String, count: UInt64) {
        self.period = period
        self.count = count
    }
}

#if compiler(>=6)
extension TimeBucket: Sendable {}
#endif


extension TimeBucket: Equatable, Hashable {
    public static func ==(lhs: TimeBucket, rhs: TimeBucket) -> Bool {
        if lhs.period != rhs.period {
            return false
        }
        if lhs.count != rhs.count {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(period)
        hasher.combine(count)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTimeBucket: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TimeBucket {
        return
            try TimeBucket(
                period: FfiConverterString.read(from: &buf), 
                count: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: TimeBucket, into buf: inout [UInt8]) {
        FfiConverterString.write(value.period, into: &buf)
        FfiConverterUInt64.write(value.count, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTimeBucket_lift(_ buf: RustBuffer) throws -> TimeBucket {
    return try FfiConverterTypeTimeBucket.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTimeBucket_lower(_ value: TimeBucket) -> RustBuffer {
    return FfiConverterTypeTimeBucket.lower(value)
}


public struct UserStats {
    public var userId: String
    public var totalMemories: UInt64
    public var totalEntities: UInt64
    public var totalRelationships: UInt64
    public var earliestMemory: String?
    public var latestMemory: String?
    public var uniqueAgents: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(userId: String, totalMemories: UInt64, totalEntities: UInt64, totalRelationships: UInt64, earliestMemory: String?, latestMemory: String?, uniqueAgents: UInt64) {
        self.userId = userId
        self.totalMemories = totalMemories
        self.totalEntities = totalEntities
        self.totalRelationships = totalRelationships
        self.earliestMemory = earliestMemory
        self.latestMemory = latestMemory
        self.uniqueAgents = uniqueAgents
    }
}

#if compiler(>=6)
extension UserStats: Sendable {}
#endif


extension UserStats: Equatable, Hashable {
    public static func ==(lhs: UserStats, rhs: UserStats) -> Bool {
        if lhs.userId != rhs.userId {
            return false
        }
        if lhs.totalMemories != rhs.totalMemories {
            return false
        }
        if lhs.totalEntities != rhs.totalEntities {
            return false
        }
        if lhs.totalRelationships != rhs.totalRelationships {
            return false
        }
        if lhs.earliestMemory != rhs.earliestMemory {
            return false
        }
        if lhs.latestMemory != rhs.latestMemory {
            return false
        }
        if lhs.uniqueAgents != rhs.uniqueAgents {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(userId)
        hasher.combine(totalMemories)
        hasher.combine(totalEntities)
        hasher.combine(totalRelationships)
        hasher.combine(earliestMemory)
        hasher.combine(latestMemory)
        hasher.combine(uniqueAgents)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUserStats: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UserStats {
        return
            try UserStats(
                userId: FfiConverterString.read(from: &buf), 
                totalMemories: FfiConverterUInt64.read(from: &buf), 
                totalEntities: FfiConverterUInt64.read(from: &buf), 
                totalRelationships: FfiConverterUInt64.read(from: &buf), 
                earliestMemory: FfiConverterOptionString.read(from: &buf), 
                latestMemory: FfiConverterOptionString.read(from: &buf), 
                uniqueAgents: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: UserStats, into buf: inout [UInt8]) {
        FfiConverterString.write(value.userId, into: &buf)
        FfiConverterUInt64.write(value.totalMemories, into: &buf)
        FfiConverterUInt64.write(value.totalEntities, into: &buf)
        FfiConverterUInt64.write(value.totalRelationships, into: &buf)
        FfiConverterOptionString.write(value.earliestMemory, into: &buf)
        FfiConverterOptionString.write(value.latestMemory, into: &buf)
        FfiConverterUInt64.write(value.uniqueAgents, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUserStats_lift(_ buf: RustBuffer) throws -> UserStats {
    return try FfiConverterTypeUserStats.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUserStats_lower(_ value: UserStats) -> RustBuffer {
    return FfiConverterTypeUserStats.lower(value)
}


public enum MemmeError: Swift.Error {

    
    
    case Runtime(msg: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMemmeError: FfiConverterRustBuffer {
    typealias SwiftType = MemmeError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MemmeError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Runtime(
            msg: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MemmeError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Runtime(msg):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(msg, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMemmeError_lift(_ buf: RustBuffer) throws -> MemmeError {
    return try FfiConverterTypeMemmeError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMemmeError_lower(_ value: MemmeError) -> RustBuffer {
    return FfiConverterTypeMemmeError.lower(value)
}


extension MemmeError: Equatable, Hashable {}




extension MemmeError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}







/**
 * HTTP transport callback — implemented by the host app.
 *
 * The host provides this via `newWithHttpClient`. All LLM and embedding
 * API calls are routed through this single callback.
 */
public protocol HttpClient: AnyObject, Sendable {
    
    /**
     * Perform a synchronous HTTP POST.
     *
     * - `url`: full URL (e.g. `https://api.openai.com/v1/chat/completions`)
     * - `headers`: alternating key/value pairs: `["Authorization", "Bearer sk-...", "Content-Type", "application/json"]`
     * - `body`: JSON request body as a string.
     *
     * Returns the response body as a string, or throws on network/HTTP error.
     */
    func post(url: String, headers: [String], body: String) throws  -> String
    
}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceHttpClient {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceHttpClient] = [UniffiVTableCallbackInterfaceHttpClient(
        post: { (
            uniffiHandle: UInt64,
            url: RustBuffer,
            headers: RustBuffer,
            body: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> String in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceHttpClient.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.post(
                     url: try FfiConverterString.lift(url),
                     headers: try FfiConverterSequenceString.lift(headers),
                     body: try FfiConverterString.lift(body)
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterString.lower($0) }
            uniffiTraitInterfaceCallWithError(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn,
                lowerError: FfiConverterTypeMemmeError_lower
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfaceHttpClient.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface HttpClient: handle missing in uniffiFree")
            }
        }
    )]
}

private func uniffiCallbackInitHttpClient() {
    uniffi_memme_ffi_fn_init_callback_vtable_httpclient(UniffiCallbackInterfaceHttpClient.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceHttpClient {
    fileprivate static let handleMap = UniffiHandleMap<HttpClient>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceHttpClient : FfiConverter {
    typealias SwiftType = HttpClient
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceHttpClient_lift(_ handle: UInt64) throws -> HttpClient {
    return try FfiConverterCallbackInterfaceHttpClient.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceHttpClient_lower(_ v: HttpClient) -> UInt64 {
    return FfiConverterCallbackInterfaceHttpClient.lower(v)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionFloat: FfiConverterRustBuffer {
    typealias SwiftType = Float?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterFloat.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterFloat.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionDouble: FfiConverterRustBuffer {
    typealias SwiftType = Double?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterDouble.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterDouble.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeMemoryResult: FfiConverterRustBuffer {
    typealias SwiftType = MemoryResult?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeMemoryResult.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeMemoryResult.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterSequenceString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterSequenceString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeChatMessage: FfiConverterRustBuffer {
    typealias SwiftType = [ChatMessage]

    public static func write(_ value: [ChatMessage], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeChatMessage.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ChatMessage] {
        let len: Int32 = try readInt(&buf)
        var seq = [ChatMessage]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeChatMessage.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeEntity: FfiConverterRustBuffer {
    typealias SwiftType = [Entity]

    public static func write(_ value: [Entity], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeEntity.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Entity] {
        let len: Int32 = try readInt(&buf)
        var seq = [Entity]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeEntity.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeEntityStat: FfiConverterRustBuffer {
    typealias SwiftType = [EntityStat]

    public static func write(_ value: [EntityStat], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeEntityStat.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [EntityStat] {
        let len: Int32 = try readInt(&buf)
        var seq = [EntityStat]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeEntityStat.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeGraphRelation: FfiConverterRustBuffer {
    typealias SwiftType = [GraphRelation]

    public static func write(_ value: [GraphRelation], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeGraphRelation.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [GraphRelation] {
        let len: Int32 = try readInt(&buf)
        var seq = [GraphRelation]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeGraphRelation.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeHistoryRecord: FfiConverterRustBuffer {
    typealias SwiftType = [HistoryRecord]

    public static func write(_ value: [HistoryRecord], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeHistoryRecord.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [HistoryRecord] {
        let len: Int32 = try readInt(&buf)
        var seq = [HistoryRecord]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeHistoryRecord.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMemoryResult: FfiConverterRustBuffer {
    typealias SwiftType = [MemoryResult]

    public static func write(_ value: [MemoryResult], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMemoryResult.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [MemoryResult] {
        let len: Int32 = try readInt(&buf)
        var seq = [MemoryResult]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMemoryResult.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeTimeBucket: FfiConverterRustBuffer {
    typealias SwiftType = [TimeBucket]

    public static func write(_ value: [TimeBucket], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeTimeBucket.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [TimeBucket] {
        let len: Int32 = try readInt(&buf)
        var seq = [TimeBucket]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeTimeBucket.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_memme_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_memme_ffi_checksum_method_memorystore_add() != 40882) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memme_ffi_checksum_method_memorystore_add_graph() != 62371) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memme_ffi_checksum_method_memorystore_add_smart() != 31635) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memme_ffi_checksum_method_memorystore_add_smart_messages() != 10892) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memme_ffi_checksum_method_memorystore_delete() != 19469) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memme_ffi_checksum_method_memorystore_delete_all() != 55440) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memme_ffi_checksum_method_memorystore_get() != 61690) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memme_ffi_checksum_method_memorystore_history() != 16498) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memme_ffi_checksum_method_memorystore_hybrid_search() != 54484) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memme_ffi_checksum_method_memorystore_list() != 33767) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memme_ffi_checksum_method_memorystore_memory_frequency() != 32415) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memme_ffi_checksum_method_memorystore_rebuild_fts_index() != 57926) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memme_ffi_checksum_method_memorystore_reset() != 23963) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memme_ffi_checksum_method_memorystore_search() != 56064) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memme_ffi_checksum_method_memorystore_search_graph() != 32550) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memme_ffi_checksum_method_memorystore_top_entities() != 38357) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memme_ffi_checksum_method_memorystore_update() != 28204) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memme_ffi_checksum_method_memorystore_user_stats() != 58728) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memme_ffi_checksum_constructor_memorystore_new_mock() != 39271) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memme_ffi_checksum_constructor_memorystore_new_with_http_client() != 60345) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_memme_ffi_checksum_method_httpclient_post() != 238) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitHttpClient()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureMemmeFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all