/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Memory result returned to JavaScript. */
export interface MemoryResult {
  id: string
  content: string
  userId: string
  agentId?: string
  appId?: string
  runId?: string
  score?: number
  createdAt: string
  updatedAt: string
  metadata?: string
  importance?: number
  accessCount?: number
  immutable: boolean
  expirationDate?: string
  categories?: Array<string>
  memoryType?: string
  retention?: number
  stability?: number
  privacy: string
  eventTime?: string
  episodeId?: string
  sessionId?: string
}
/** A chat message for smart operations. */
export interface ChatMessage {
  role: string
  content: string
}
/** A chat message with a stable caller-provided event ID for safe replay. */
export interface IdentifiedChatMessage {
  eventId: string
  role: string
  content: string
  timestamp?: string
}
/** Entity in the knowledge graph. */
export interface Entity {
  id: string
  name: string
  entityType?: string
  userId: string
}
/** Relationship in the knowledge graph. */
export interface GraphRelation {
  id: string
  source: string
  sourceId: string
  target: string
  targetId: string
  relationType: string
  userId: string
  description?: string
}
/** A history record. */
export interface HistoryRecord {
  id: string
  memoryId: string
  oldMemory?: string
  newMemory: string
  event: string
  createdAt: string
}
/** User statistics. */
export interface UserStats {
  userId: string
  totalMemories: number
  totalEntities: number
  totalRelationships: number
  earliestMemory?: string
  latestMemory?: string
  uniqueAgents: number
}
/** Memory count per time period. */
export interface TimeBucket {
  period: string
  count: number
}
/** Top entity by relationship count. */
export interface EntityStat {
  name: string
  entityType?: string
  relationshipCount: number
}
/** An episode (compressed understanding of a session). */
export interface Episode {
  episodeId: string
  title: string
  summary: string
  startedAt: string
  endedAt?: string
  significance: number
  outcome?: string
  sourceId?: string
  eventIds: Array<string>
  sessionIds: Array<string>
  userId: string
  createdAt: string
  lastRecalled?: string
  recallCount: number
  storageStrength: number
  retrievalStrength: number
  score?: number
}
/** A stream event (single event in a session). */
export interface StreamEvent {
  eventId: string
  eventType: string
  content: string
  timestamp: string
  sessionId?: string
  sourceId?: string
  userId: string
  parentId?: string
  metadata?: string
  processed: boolean
  purifiedContent?: string
  location?: string
}
/** A session (immutable event container). */
export interface Session {
  sessionId: string
  userId: string
  sourceId?: string
  startedAt: string
  endedAt?: string
  metadata?: string
  createdAt: string
  eventCount: number
}
/** Session context assembled for retrieval-augmented generation. */
export interface SessionContext {
  sessionId: string
  events: Array<StreamEvent>
  tokensUsed: number
  tokenBudget: number
  episodeSummary?: string
  purifiedCount: number
  rawCount: number
}
/** An identity trait extracted from memories. */
export interface IdentityTrait {
  traitId: string
  traitType: string
  content: string
  confidence: number
  evidenceIds: Array<string>
  userId: string
  createdAt: string
  updatedAt?: string
}
/** A meditation (deep processing) record. */
export interface MeditationRecord {
  meditationId: string
  triggeredBy: string
  startedAt: string
  finishedAt?: string
  status: string
  userId: string
  eventsProcessed: number
  episodesCreated: number
  memoriesCreated: number
  memoriesUpdated: number
  memoriesDecayed: number
  entitiesCreated: number
  relationsCreated: number
  conflictsFound: number
  journal?: string
  metadata?: string
}
/** Result of appending events to a session. */
export interface AppendEventsResult {
  sessionId: string
  eventsAppended: number
  eventsReplayed: number
  embeddingPending: number
  totalUnprocessed: number
  compactNeeded: boolean
}
/** Result of compacting a session into an episode. */
export interface CompactResult {
  sessionId: string
  episodeId: string
  memories: Array<MemoryResult>
  eventsProcessed: number
}
/** Graph search result. */
export interface GraphSearchResult {
  entities: Array<Entity>
  relations: Array<GraphRelation>
}
/** The main MemMe memory store. */
export declare class MemoryStore {
  /**
   * Create a new MemoryStore with mock embedder (for testing).
   * Pass a trusted VexDB-Lite extension path explicitly, or omit it to use
   * MEMME_VEXDB_LITE_EXTENSION.
   */
  static newMock(dbPath?: string | undefined | null, dims?: number | undefined | null, vexdbExtensionPath?: string | undefined | null): MemoryStore
  /**
   * Create a new MemoryStore with mock embedder AND mock LLM (for E2E testing).
   * The mock LLM returns pre-scripted responses in order.
   * Pass an array of JSON strings that the LLM should return.
   */
  static newMockWithLlm(responses: Array<string>, dbPath?: string | undefined | null, dims?: number | undefined | null, vexdbExtensionPath?: string | undefined | null): MemoryStore
  /** Create a new MemoryStore with OpenAI-compatible embedder. */
  static newOpenai(apiKey: string, dbPath?: string | undefined | null, baseUrl?: string | undefined | null, model?: string | undefined | null, dims?: number | undefined | null, vexdbExtensionPath?: string | undefined | null): MemoryStore
  /** Configure LLM provider at runtime. Call once after construction. */
  setLlmProvider(apiKey: string, model: string, baseUrl?: string | undefined | null): void
  /**
   * Backup the database to a file path.
   * Returns metadata about the backup (size, memory count, schema version).
   */
  backupToPath(path: string): any
  /**
   * Restore the database from a backup file.
   * **Warning**: The caller must re-create the MemoryStore after calling this.
   */
  restoreFromBackup(backupPath: string): void
  /** Run diagnostic checks on storage, embedder, and LLM. */
  diagnose(): any
  /** Check if an LLM provider is configured. */
  hasLlm(): boolean
  /** Persist LLM configuration to the database. */
  saveLlmConfig(apiKey: string, model: string, baseUrl: string): void
  /** Load persisted LLM configuration. Returns [apiKey, model, baseUrl] or null. */
  loadLlmConfig(): Array<string> | null
  /** Add a memory (vector dedup, no LLM). */
  add(content: string, userId: string, agentId?: string | undefined | null, runId?: string | undefined | null, metadata?: string | undefined | null): Promise<MemoryResult>
  /** Search memories. */
  search(query: string, userId: string, agentId?: string | undefined | null, runId?: string | undefined | null, limit?: number | undefined | null, threshold?: number | undefined | null): Promise<Array<MemoryResult>>
  /** Get a memory by ID. */
  get(id: string): Promise<MemoryResult | null>
  /** Update a memory. */
  update(id: string, content: string): Promise<MemoryResult>
  /** Delete a memory. */
  delete(id: string): Promise<void>
  /** List memories. */
  list(userId: string, agentId?: string | undefined | null, runId?: string | undefined | null, limit?: number | undefined | null): Promise<Array<MemoryResult>>
  /**
   * Hybrid search (vector + FTS with RRF fusion).
   *
   * RRF weights are configured at store construction time.
   */
  hybridSearch(query: string, userId: string, agentId?: string | undefined | null, runId?: string | undefined | null, limit?: number | undefined | null): Promise<Array<MemoryResult>>
  /** Rebuild FTS index. */
  rebuildFtsIndex(): Promise<void>
  /** Delete all memories matching filters. */
  deleteAll(userId: string, agentId?: string | undefined | null, runId?: string | undefined | null, appId?: string | undefined | null): Promise<number>
  /** Get change history for a memory. */
  history(memoryId: string): Promise<Array<HistoryRecord>>
  /** Reset the entire store — delete ALL data. Destructive. */
  reset(): Promise<void>
  /** Append chat messages as events to a session. Returns whether compact is needed. */
  appendEvents(sessionId: string, messages: Array<ChatMessage>, userId: string, metadata?: string | undefined | null): Promise<AppendEventsResult>
  /** Append events with stable IDs. Exact replays are accepted; conflicting reuse of an ID is rejected. */
  appendEventsIdempotent(sessionId: string, messages: Array<IdentifiedChatMessage>, userId: string, metadata?: string | undefined | null): Promise<AppendEventsResult>
  /** Compact a session: extract memories + create episode from unprocessed events. */
  compact(sessionId: string): Promise<CompactResult>
  /** Get a session by ID. */
  getSession(sessionId: string): Promise<Session | null>
  /** List sessions for a user. */
  listSessions(userId: string, sourceId?: string | undefined | null, since?: string | undefined | null, until?: string | undefined | null, limit?: number | undefined | null, offset?: number | undefined | null): Promise<Array<Session>>
  /** Delete a session and its events. */
  deleteSession(sessionId: string): Promise<void>
  /** Get events in a session (paginated). */
  getSessionEvents(sessionId: string, limit?: number | undefined | null, offset?: number | undefined | null): Promise<Array<StreamEvent>>
  /** Assemble session context for RAG with token budget. */
  getSessionContext(sessionId: string, tokenBudget?: number | undefined | null, includeSummary?: boolean | undefined | null, maxEvents?: number | undefined | null): Promise<SessionContext>
  /** List episodes for a user. */
  listEpisodes(userId: string, limit?: number | undefined | null, offset?: number | undefined | null, since?: string | undefined | null, until?: string | undefined | null): Promise<Array<Episode>>
  /** Get an episode by ID. */
  getEpisode(episodeId: string): Promise<Episode | null>
  /** Get messages (events) in an episode. */
  getEpisodeMessages(episodeId: string, limit?: number | undefined | null, offset?: number | undefined | null): Promise<Array<StreamEvent>>
  /** Search episodes by semantic similarity. */
  searchEpisodes(query: string, userId: string, limit?: number | undefined | null): Promise<Array<Episode>>
  /** Search messages within an episode by semantic similarity. */
  searchEpisodeMessages(episodeId: string, query: string, limit?: number | undefined | null): Promise<Array<StreamEvent>>
  /** Delete an episode. */
  deleteEpisode(episodeId: string): Promise<void>
  /** List all identity traits for a user. */
  listIdentityTraits(userId: string): Promise<Array<IdentityTrait>>
  /** Add or update an identity trait. */
  addIdentityTrait(traitType: string, content: string, userId: string, confidence?: number | undefined | null, evidenceIds?: Array<string> | undefined | null): Promise<IdentityTrait>
  /** Trigger deep processing (meditation): decay, extraction, graph, identity. */
  meditate(userId: string, triggeredBy: string, since?: string | undefined | null): Promise<MeditationRecord>
  /** Add graph with LLM. */
  addGraph(text: string, userId: string, llmApiKey: string, llmModel?: string | undefined | null, llmBaseUrl?: string | undefined | null): Promise<GraphSearchResult>
  /** Search graph (no LLM). */
  searchGraph(query: string, userId: string, depth?: number | undefined | null): Promise<GraphSearchResult>
  /** Get summary statistics for a user. */
  userStats(userId: string): Promise<UserStats>
  /** Get memory creation frequency by time period. */
  memoryFrequency(userId: string, granularity: string, limit?: number | undefined | null): Promise<Array<TimeBucket>>
  /** Get top entities by relationship count. */
  topEntities(userId: string, limit?: number | undefined | null): Promise<Array<EntityStat>>
}
